site_name: "Lyrics"
site_url: https://ev-ref-kirchengemeinde-neunkirchen.github.io/lyrics/
site_description: "Liedtexte und weitere Inhalte für Open-Air-Gottesdienste der Ev.-Ref. Kirchengemeinde Neunkirchen"
copyright: "Ev.-Ref. Kirchengemeinde Neunkirchen"
theme: 
  name: readthedocs
  locale: de
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - search
nav:
  - index.md
  - Kommt_herbei_singt_dem_Herrn.md
  - Ich_stehe_und_strecke_meine_Hände_zu_dir.md
  - Lob_Anbetung_Ruhm_und_Ehre.md
  - Apostolisches_Glaubensbekenntnis.md
  - Herr ich sehe deine Welt-lyrics.md
  - Gott_gab_uns_Atem_damit_wir_leben.md
  - Vater_unser.md
  - Sei_behütet_auf_deinen_Wegen.md
