site_name: "Lyrics"
site_url: https://ev-ref-kirchengemeinde-neunkirchen.github.io/lyrics/
site_description: "Liedtexte und weitere Inhalte für Open-Air-Gottesdienste der Ev.-Ref. Kirchengemeinde Neunkirchen"
copyright: "Ev.-Ref. Kirchengemeinde Neunkirchen"
theme: 
  name: readthedocs
  locale: de
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - search
nav:
  - index.md
  - All_morgen_ist_ganz_frisch_und_neu.md
  - Herr_deine_Güte_reicht_soweit_der_Himmel_ist.md
  - Lobet_den_Herren.md
  - Apostolisches_Glaubensbekenntnis.md
  - Von_guten_Mächten.md
  - Vater_unser.md
  - Möge_die_Straße.md
