site_name: "Lyrics"
site_url: https://ev-ref-kirchengemeinde-neunkirchen.github.io/lyrics/
site_description: "Liedtexte und weitere Inhalte für Open-Air-Gottesdienste der Ev.-Ref. Kirchengemeinde Neunkirchen"
copyright: "Ev.-Ref. Kirchengemeinde Neunkirchen"
theme: 
  name: readthedocs
  locale: de
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - search
nav:
  - index.md
  - Du_hast_uns_Herr_gerufen.md
  - Herr_mach_mich_zu_einem_Werkzeug_deines_Friedens.md
  - Ich_lobe_meinen_Gott_von_ganzem_Herzen.md
  - Apostolisches_Glaubensbekenntnis.md
  - Lob_Anbetung_Ruhm_und_Ehre.md
  - Wenn_das_Brot_das_wir_teilen.md
  - Schuldbekenntnis_LzHuE.md
  - Vater_unser.md
  - Nun_danket_alle_Gott.md
  - Sei_behütet_auf_deinen_Wegen.md
