site_name: "Lyrics"
site_url: https://ev-ref-kirchengemeinde-neunkirchen.github.io/lyrics/
site_description: "Liedtexte und weitere Inhalte für Open-Air-Gottesdienste der Ev.-Ref. Kirchengemeinde Neunkirchen"
copyright: "Ev.-Ref. Kirchengemeinde Neunkirchen"
theme: 
  name: readthedocs
  locale: de
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - search
nav:
  - index.md
  - Ich_lobe_meinen_Gott_von_ganzem_Herzen.md
  - Ich_lobe_meinen_Gott_der_aus_der_Tiefe_mich_holt.md
  - Apostolisches_Glaubensbekenntnis.md
  - Gottes_Liebe_ist_wie_die_Sonne.md
  - Liebe_ist_nicht_nur_ein_Wort.md
  - Halleluja_kyrie_eleison.md
  - Vater_unser.md
  - Geh_in_Gottes_Frieden.md
