site_name: "Lyrics"
site_url: https://ev-ref-kirchengemeinde-neunkirchen.github.io/lyrics/
site_description: "Liedtexte und weitere Inhalte für Open-Air-Gottesdienste der Ev.-Ref. Kirchengemeinde Neunkirchen"
copyright: "Ev.-Ref. Kirchengemeinde Neunkirchen"
theme: 
  name: readthedocs
  locale: de
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - search
nav:
  - index.md
  - Morgenlicht_leuchtet.md
  - Alle_Sorgen_werft_auf_ihn.md
  - Laudate_omnes_gentes.md
  - Apostolisches_Glaubensbekenntnis.md
  - Wenn_die_Last_der_Welt.md
  - Meine_Hoffnung_und_meine_Freude.md
  - Vater_unser.md
  - Komm_Herr_segne_uns.md
